# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Ubuntu 1604

steps:

- task: DockerCompose@0
  displayName: 'Build services Images'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'china-acr-azuredevops101'
    action: 'Build services'

- task: DockerCompose@0
  displayName: 'Push Service Images'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'china-acr-azuredevops101'
    action: 'Push services'

