version: '3'

services:
  redis:
    image: lib/redis
    build:
      context: .
      dockerfile: dockerfile.redis
  db:
    image: postgres
    build:
      context: .
      dockerfile: dockerfile.postgres