version: '3'

services:
  redis:
    image: lib/redis:alpine
    build:
      context: .
      dockerfile: Dockerfile.redis
  postgres:
    image: lib/postgres:9.4
    build:
      context: .
      dockerfile: Dockerfile.postgres