version: '3'

services:
  redis:
    image: lib/redis
    build:
      context: .
      dockerfile: Dockerfile.redis
  postgres:
    image: lib/postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres